class Item {
  const Item({
    required this.id,
    required this.firmId,
    required this.itemCode,
    required this.itemName,
    required this.itemGroup,
    required this.subGroup,
    required this.mfgBy,
    required this.unitOfMeasure,
    required this.rateRetail,
    required this.dealerRate,
    required this.purchaseRate,
    required this.mrp,
    required this.cutAverage,
    required this.boxPack,
    required this.looseQuantity,
    required this.hsnCode,
    required this.sgst,
    required this.cgst,
    required this.igst,
    required this.gstCalculation,
    required this.hsnDescription,
    required this.hsnUqc,
    required this.rolMin,
    required this.rolMax,
    required this.openingStockQuantity,
    required this.openingStockAmount,
    required this.openingStockNos,
    required this.calculateOn,
    required this.rateUpdate,
    required this.showInStockReport,
    required this.active,
    required this.discount,
    required this.remarks,
  });

  final int? id;
  final int firmId;
  final String itemCode, itemName, itemGroup, subGroup, mfgBy, unitOfMeasure;
  final String rateRetail,
      dealerRate,
      purchaseRate,
      mrp,
      cutAverage,
      boxPack,
      looseQuantity;
  final String hsnCode,
      sgst,
      cgst,
      igst,
      gstCalculation,
      hsnDescription,
      hsnUqc;
  final String rolMin,
      rolMax,
      openingStockQuantity,
      openingStockAmount,
      openingStockNos;
  final String calculateOn,
      rateUpdate,
      showInStockReport,
      active,
      discount,
      remarks;

  factory Item.fromMap(Map<String, Object?> map) => Item(
    id: map['id'] as int?,
    firmId: map['firm_id'] as int? ?? 0,
    itemCode: map['item_code'] as String,
    itemName: map['item_name'] as String,
    itemGroup: map['item_group'] as String,
    subGroup: map['sub_group'] as String,
    mfgBy: map['mfg_by'] as String,
    unitOfMeasure: map['unit_of_measure'] as String,
    rateRetail: map['rate_retail'] as String,
    dealerRate: map['dealer_rate'] as String,
    purchaseRate: map['purchase_rate'] as String,
    mrp: map['mrp'] as String,
    cutAverage: map['cut_average'] as String,
    boxPack: map['box_pack'] as String,
    looseQuantity: map['loose_quantity'] as String,
    hsnCode: map['hsn_code'] as String,
    sgst: map['sgst'] as String,
    cgst: map['cgst'] as String,
    igst: map['igst'] as String,
    gstCalculation: map['gst_calculation'] as String,
    hsnDescription: map['hsn_description'] as String,
    hsnUqc: map['hsn_uqc'] as String,
    rolMin: map['rol_min'] as String,
    rolMax: map['rol_max'] as String,
    openingStockQuantity: map['opening_stock_quantity'] as String,
    openingStockAmount: map['opening_stock_amount'] as String,
    openingStockNos: map['opening_stock_nos'] as String,
    calculateOn: map['calculate_on'] as String,
    rateUpdate: map['rate_update'] as String,
    showInStockReport: map['show_in_stock_report'] as String,
    active: map['active'] as String,
    discount: map['discount'] as String,
    remarks: map['remarks'] as String,
  );

  Map<String, Object?> toMap() => {
    'firm_id': firmId,
    'item_code': itemCode,
    'item_name': itemName,
    'item_group': itemGroup,
    'sub_group': subGroup,
    'mfg_by': mfgBy,
    'unit_of_measure': unitOfMeasure,
    'rate_retail': rateRetail,
    'dealer_rate': dealerRate,
    'purchase_rate': purchaseRate,
    'mrp': mrp,
    'cut_average': cutAverage,
    'box_pack': boxPack,
    'loose_quantity': looseQuantity,
    'hsn_code': hsnCode,
    'sgst': sgst,
    'cgst': cgst,
    'igst': igst,
    'gst_calculation': gstCalculation,
    'hsn_description': hsnDescription,
    'hsn_uqc': hsnUqc,
    'rol_min': rolMin,
    'rol_max': rolMax,
    'opening_stock_quantity': openingStockQuantity,
    'opening_stock_amount': openingStockAmount,
    'opening_stock_nos': openingStockNos,
    'calculate_on': calculateOn,
    'rate_update': rateUpdate,
    'show_in_stock_report': showInStockReport,
    'active': active,
    'discount': discount,
    'remarks': remarks,
  };
}
